languages:
   Ruby: false
   JavaScript: true
   Python: true
   PHP: false
exclude_paths:
- "build/*"
- "support/*"
- "WAIL.spec"
- "bundledApps/heritrix-3.2.0/*"
- "bundledApps/html/*"
- "bundledApps/tomcat/*"
